# Tests are run from the Typescript side, not here.
- op: remove
  path: /jobs/cargo-test

# Everything needs to run in the native directory.
- op: add
  path: /defaults
  value:
    run:
      working-directory: native
