sudo: false
language: rust
rust:
- 1.29.1

matrix:
  include:
  - name: "Linux - Node 8"
    os: linux
    env: TRAVIS_NODE_VERSION="8"
  - name: "OSX - Node 8"
    os: osx
    env: TRAVIS_NODE_VERSION="8"
  - name: "Linux - Node 10"
    os: linux
    env: TRAVIS_NODE_VERSION="10"
  - name: "OSX - Node 10"
    os: osx
    env: TRAVIS_NODE_VERSION="10"

before_install:
  # install our own yarn to make things work on osx
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH=$HOME/.yarn/bin:$PATH

install:
# install our own nodejs to get a reasonable version
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

branches:
  only:
  - master
  - node-pre-gyp #TODO remove
  - travis-github-upload #TODO remove
notifications:
  email:
    on_success: change
#    on_failure: always
cache:
    yarn: true
    cargo: true
    directories:
        - node_modules
before_script:
    - rustup component add rustfmt-preview
script:
    - pushd native/ && cargo fmt -- --check && popd
    - yarn || true
    - yarn run compile
    - yarn test
deploy:
    provider: releases
    api_key:
        secure: bqeFXHY/NMLwbyIY4ch/KFhTyEpZFeO8MeHKTKEPdqk7OPh77aShiixUNNi1oBv8Nw4sjqM1nhx+j5UlPcbyPD4IWlosgPkYpNzZgcSUM61UEaSJ7oa3QYi6fT/qawTeGX7g7iVV72Sz9NMk+dSTZMSZM02iBcFczGgsfyq+cyV5HJiyP7DcSASARsXXt72D4B9GKVmqa6n5Dk8FSwE024h/duLtzPAEWAxK3eJsaDN0OdJKXq7/nTtEf0Hblbl0hkO4ce3RVZQg3nm0k1IDabglEMto9t6BavZobEm9YZoeePhAdH/WybSGBvJKwN29D9fNvNBf8UDBxa8gL3pIdLM8yucBWL888ku/zs6cAlg2BcY7e8gOiVuYUh8pznXPpYbo65N1w+EzuwQk/MgHPr/Fnh7Uois+1ymtQhxXbFqvqDXFDCHh7P3n4H6uN15iTpqdvHkC1HCnebL47bW657AD1spB6pNefWOUVpa66abWXmEoRakpGHaIdbhlKoaPo1tkImlSRbW/3Yt4zRSn3Dv1Va7vrRLtoJ4mD/ilD7QhmJK/ksqncS02hCQjiTExplS+2VjV4kZA4+lNmkTo3EyhS+DKZrPcXa/AMu/n7yFXpRNX6gUtDbbp8+QlODbOauooaL82RNb8Xw46jiqtUapKpo+dYOFwWFQgmSi5PKQ=
    file_glob: true
    file: bin-package/*
    skip_cleanup: true
    on:
        tags: true
