sudo: false
language: rust
rust:
- 1.29.1

stages:
  - compile
  - test
  - npm publish

jobs:
  include:
    # 
  - name: "compile and test"
    stage: "compile"
    os: linux
    env: TRAVIS_NODE_VERSION="8"
    if: commit_message =~ [build]
    script:
      - yarn install --ignore-scripts
      - yarn run compile
      - yarn test

  - name: "Linux - Node 8"
    os: linux
    env: TRAVIS_NODE_VERSION="8"
    if: (branch = master AND tag = /^v\d+\.\d+\.\d+.*$/ ) OR type = pull_request
  - name: "OSX - Node 8"
    os: osx
    env: TRAVIS_NODE_VERSION="8"
    if: (branch = master AND tag = /^v\d+\.\d+\.\d+.*$/ ) OR type = pull_request
  - name: "Linux - Node 10"
    os: linux
    env: TRAVIS_NODE_VERSION="10"
    if: (branch = master AND tag = /^v\d+\.\d+\.\d+.*$/ ) OR type = pull_request
  - name: "OSX - Node 10"
    os: osx
    env: TRAVIS_NODE_VERSION="10"
    if: (branch = master AND tag = /^v\d+\.\d+\.\d+.*$/ ) OR type = pull_request

  - stage: "NPM publish"
    os: linux
    env: TRAVIS_NODE_VERSION="8"
    if: branch = master AND tag = /^v\d+\.\d+\.\d+.*$/
    script: echo "Deploying to NPM..."


before_install:
  # install our own yarn to make things work on osx
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH=$HOME/.yarn/bin:$PATH

install:
# install our own nodejs to get a reasonable version
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

# notifications:
#   email:
    # on_success: change
#    on_failure: always
cache:
    yarn: true
    cargo: true
    directories:
        - node_modules
before_script:
    - rustup component add rustfmt-preview
script:
    - pushd native/ && cargo fmt -- --check && popd
    - node publish.js

