sudo: false
language: rust
rust:
- 1.29.1

matrix:
  include:
  - name: "Linux - Node 8"
    os: linux
    TRAVIS_NODE_VERSION="8"
  - name: "OSX - Node 8"
    os: osx
    TRAVIS_NODE_VERSION="8"
  - name: "Linux - Node 10"
    os: linux
    TRAVIS_NODE_VERSION="10"
  - name: "OSX - Node 10"
    os: osx
    TRAVIS_NODE_VERSION="10"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH=$HOME/.yarn/bin:$PATH

install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install

branches:
  only:
  - master
  - node-pre-gyp #TODO remove
notifications:
  email:
    on_success: change
#    on_failure: always
cache:
    yarn: true
    cargo: true
    directories:
        - node_modules
before_script:
    - rustup component add rustfmt-preview
script:
    - pushd native/ && cargo fmt -- --check && popd
    - yarn
    - yarn run compile
    - yarn test
