sudo: false
language: rust
rust:
- 1.29.1

matrix:
  include:
  - name: "Linux"
    os: linux
    node_js:
      - "8"
  - name: "OSX"
    os: osx
    node_js:
      - "8"

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH=$HOME/.yarn/bin:$PATH

branches:
  only:
  - master
  - node-pre-gyp #TODO remove
notifications:
  email:
    on_success: change
#    on_failure: always
cache:
    yarn: true
    cargo: true
    directories:
        - node_modules
before_script:
    - rustup component add rustfmt-preview
script:
    - pushd native/ && cargo fmt -- --check && popd
    - yarn
    - yarn run compile
    - yarn test
