[package]
name = "recrypt-node-binding"
version = "0.4.1"
authors = ["IronCore Labs <code@ironcorelabs.com>"]

[lib]
name = "recrypt_node"
crate-type = ["dylib"]

[dependencies]
rand = "~0.6.1"
recrypt = "~0.6"
neon = "~0.2.0"

[build-dependencies]
neon-build = "0.2.0"

[profile.release]
lto = true
debug = false
