[package]
name = "recrypt-node-binding"
version = "0.4.1"
authors = ["IronCore Labs <code@ironcorelabs.com>"]

[lib]
name = "recrypt_node"
crate-type = ["dylib"]

[dependencies]
rand = "0.5.5"
#recrypt = "0.3.0"
recrypt = { git = "https://github.com/IronCoreLabs/recrypt-rs"}
neon = "0.2.0"

[build-dependencies]
neon-build = "0.2.0"

[profile.release]
lto = true
debug = false
