name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 14 * * 1
jobs:
  rust-ci:
    uses: IronCoreLabs/workflows/.github/workflows/rust-ci.yaml@rust-ci-v2
    with:
      # only run build, only on the toolchain version
      # typescript runs the real tests
      test_matrix_include: '[{ rust_version: "", build_only: true }]'
    secrets: inherit
